server:
  port: 8001

spring:
  application:
    name: user-service
  datasource: #数据源
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false  # 数据库的 JDBC URL
    username:    #数据库的登录用户名
    password:    #数据库的登录密码
    driver-class-name: com.mysql.jdbc.Driver #数据库驱动
  #邮箱验证码配置
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com;163邮箱是smtp.163.com
    host: smtp.163.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username:
    #授权码
    password:
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis:
  mapper-locations: classpath:mapper/user/*.xml,classpath:mapper/msg/*.xml
